ignore:
  # CVE-2025-7709: Integer overflow in SQLite FTS5 extension
  # Medium severity vulnerability in libsqlite3-0 version 3.46.1-7
  # No fix available in Debian Trixie - marked as "wont-fix"
  - vulnerability: "CVE-2025-7709"
    package:
      name: "libsqlite3-0"
    fix-state: "wont-fix"
